# Generated by Django 3.2.7 on 2021-10-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ('recipe__name',), 'verbose_name': 'List of favorite recipes'},
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='shoppingcard',
            name='recipe',
            field=models.ManyToManyField(related_name='shopping_card', to='api.Recipes', verbose_name='Recipe for shopping card'),
        ),
        migrations.AlterField(
            model_name='shoppingcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_card', to=settings.AUTH_USER_MODEL, verbose_name="User's shopping card"),
        ),
    ]
