# Generated by Django 3.2.7 on 2021-10-01 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribes',
            name='subscribe_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe_on', to=settings.AUTH_USER_MODEL, verbose_name='subscribing user'),
        ),
        migrations.AddField(
            model_name='subscribes',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL, verbose_name='subscriber'),
        ),
        migrations.AddField(
            model_name='shoppingcard',
            name='ingredients',
            field=models.ManyToManyField(to='api.Ingredients', verbose_name='Ingredients for shopping card'),
        ),
        migrations.AddField(
            model_name='shoppingcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User's shopping card"),
        ),
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Recipe's author"),
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.ManyToManyField(to='api.Ingredients'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tags', verbose_name="Recipe's tags"),
        ),
        migrations.AddField(
            model_name='favorites',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User's list of favorite recipes"),
        ),
        migrations.AddField(
            model_name='favorites',
            name='recipes',
            field=models.ManyToManyField(to='api.Recipes', verbose_name="User's favorites recipes"),
        ),
        migrations.AddConstraint(
            model_name='subscribes',
            constraint=models.UniqueConstraint(fields=('subscriber', 'subscribe_on'), name='unique_subscribe'),
        ),
    ]
