# Generated by Django 3.2.7 on 2021-10-15 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_rename_owner_favorites_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ManyToManyField(related_name='recipes_in_favorite',
                                         to='api.Recipes',
                                         verbose_name="User's favorites recipes"),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipes_of_user_favorite',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name="User's list of favorite recipes"),
        ),
        migrations.AlterField(
            model_name='shoppingcard',
            name='recipe',
            field=models.ManyToManyField(related_name='recipe_in_shopping_card',
                                         to='api.Recipes',
                                         verbose_name='Recipe for shopping card'),
        ),
    ]
