version: '2'

services:
    db:
        image: postgres:12.4-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
#        env_file:
#            - ./backend/.env
        environment:
            POSTGRES_USER: pasha
            POSTGRES_PASSWORD: pasha
#        ports:
#            - "5432:5432"
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - 80:80
        volumes:
            - static_volume:/app/backend/static
            - ./docker/nginx/development:/etc/nginx/conf.d
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../frontend/build:/usr/share/nginx/html/
            - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
            - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
        depends_on:
            - backend
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/static
        expose:
            - 8000
        depends_on:
            -   db
volumes:
    static_volume: {}
    postgres_data:
